config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index,:new,:create,:show, :destroy]
  end

  resources :posts do
    resources :comments, only: [:new, :create, :destroy]
    resources :likes, only: [:create]
  end

  namespace :api do
    resources :users do
       resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end

  root 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id', counter_cache: :posts_counter
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates_presence_of :name
  validates_numericality_of :posts_counter, only_integer: true, greater_than_or_equal_to: 0

  # Method to get the 3 most recent posts for a user
  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = Post.includes(:user).where(author_id: @user.id)
    cookies[:user_id] = @user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<header>
  <%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
</header>
<body>
  <div id="user">
    <% if @user.present? %>
      <article id="user-details">
        <h1><%= @user.name %></h1>
        <p>Number of posts: <%= @user.posts_counter.nil? ? 0 : @user.posts_counter %></p>
      </article>
    <% end %>
    <% if @user.photo.present? %>
      <img id="user-image" src="<%= @user.photo %>" alt="User Photo">
    <% end %>
  </div>
  </div>
</body>

app/views/users/index.html.erb
<header>
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
</header>
<nav class="nav">
  <%= link_to_if(user_signed_in?, 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }) %>
  <%= link_to_unless(user_signed_in?, 'Login', new_user_session_path) %>
  <%= link_to 'Sign Up', new_user_registration_path %>
</nav>

<ul class="list-group">
  <% @users.each do |user| %>
    <li class="list-group-item">
      <% if user.photo.present? %>
        <%= image_tag user.photo, class: 'user-photo' %>
      <% end %>

      <!-- Display user's username -->
      <span class="user-username"><%= user.name %></span>
      <span class="user-posts-count"> Number of posts<%= user.posts.count%></span>

      <!-- Add a link to the user's profile -->
      <%= link_to 'View Profile', user_path(user), class: 'btn btn-primary' %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<head>
  <%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-12">
        <!-- User's name and photo container with custom styles -->
        <div class="user-info-container">
          <!-- Display user's photo if available with custom style class -->
          <% if @user.photo.present? %>
            <%= image_tag @user.photo, class: 'user-photo' %>
          <% end %>

          <!-- Display user's name with custom style class -->
          <div class="user-name"><%= @user.name %></div>
        </div>
      </div>
    </div>

    <div class="bio-section">
        <h2 class="bio-header">Bio:</h2>
        <p class="bio-text"><%= @user.bio %></p>
      </div>

    <h2 class="mt-4">Posts</h2>
    <ul class="list-group">
      <% if @user.posts.empty? %>
        <li class="list-group-item">No posts for this user</li>
      <% else %>
        <% @user.recent_posts.each do |post| %>
          <%= render post %>
        <% end %>
      <% end %>
    </ul>

    <!-- "See All Posts" button -->
    <div class="button-container">
      <button><a href="<%= user_posts_path(@user) %>">See all posts</a></button>
    </div>
  </div>