config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index,:new,:create,:show, :destroy]
  end

  resources :posts do
    resources :comments, only: [:new, :create, :destroy]
    resources :likes, only: [:create]
  end

  namespace :api do
    resources :users do
       resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end

  root 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: 'post_id', counter_cache: :comments_counter, dependent: :destroy
  has_many :likes

  validates_presence_of :title
  validates_length_of :title, maximum: 250
  validates_numericality_of :comments_counter, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :likes_counter, only_integer: true, greater_than_or_equal_to: 0

  after_save :update_user_post_count

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  private

  def update_user_post_count
    author.increment!(:posts_counter) if author.present?
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    if params[:author_id].present?
      user = User.find(params[:author_id])
      @posts = user.posts
    else
      @posts = Post.all
    end

    render json: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find_by(id: params[:user_id])
    @posts = @user.posts if @user
    @posts = Post.paginate(page: params[:page], per_page: 2)
  end

  def show
    @user = current_user
    @post = Post.find(params[:id])
    @comment = Comment.new
    @like = Like.new
    cookies[:post_id] = @post.id if @post.present?
    nil unless @post.nil?
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = Post.new(post_params.merge(author_id: @user.id))
    if @post.save

      @post.update_posts_count

      redirect_to user_posts_path(@user), notice: 'Post created successfully.'
    else
      @posts = @user.posts
      render :index
    end
  end

  def destroy
    current_user = User.find(params[:author_id])
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.destroy
    @post.decrement_posts_count
    redirect_to user_posts_path(current_user), notice: 'Post deleted successfully.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :author_id, :comments_counter, :likes_counter)
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li class="list-group-item">
  <h3><%= post.title %></h3>
  <p><%= post.text %></p>
<div class="post-details">
    <span class="comments-count"><%= post.comments_counter %> Comments</span>
    <span class="likes-count"><%= post.likes_counter %> Likes</span>
  </div>
</li>

app/views/posts/index.html.erb
<%= render 'users/user' %>
<% @posts.includes(:author).each do |post| %>
  <a href="<%=  user_posts_path(@user, post) %>">
  <%= render post %></a>
  <%= render "posts/new" %>
  <%= "no comments for this post" if post.comments.empty? %>
    <div class="comments">
    <% post.recent_comments.each do |comment|%>
        <%=render comment%>
    <% end %>
    </div>
    <p id="view-post"><%= link_to 'View Post', user_post_path(@user, post) %></p>
<% end %>


<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>Create a Post</h1>
  <%= form_with(model: @post, url: posts_path) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, required: true %><br>

  <%= form.label :text %>
  <%= form.text_area :text, required: true%><br>

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<body>
  <nav class="nav">
    <%= link_to "Home", root_path %>
    <%= link_to "Back", :back %>
  </nav>
  
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= render partial: 'posts/post', locals: { post: @post } %> <br>

  <% if @post.comments.empty? %>
    <p>No comments for this post</p>
  <% else %>
    <div class="comments">
      <% @post.comments.includes(:user).each do |comment| %>
        <%= render partial: 'comments/comment', locals: { comment: comment } %>
      <% end %>
    </div>
  <% end %>

  <div class="like-comment">
    <%= render partial: 'comments/create', locals: { comment: Comment.new(post: @post), post: @post } %>
    
    <% if Like.where(user_id: User.first.id, post_id: @post.id).exists? %>
      <p id="liked">Liked</p>
    <% else %>
      <%= render partial: 'likes/create', locals: { like: Like.new(post: @post), post: @post } %>
    <% end %>
  </div>
</body>